### ISSUE TITLE
Seeking advice: How to update axum to version tungstenite 0.17

### ISSUE THREAD

**Issue by davidpdrsn** [snapview/tungstenite-rs#268]
Hey there! I'm the maintainer of the [axum](https://github.com/tokio-rs/axum) web framework. It has a [websocket feature](https://docs.rs/axum/latest/axum/extract/ws/index.html) that uses tungstenite internally. I'm seeking some advice on how to update to tungstenite 0.17.

The issue is that to not have a public dependency on tungstenite, axum has its own [`Message` enum](https://docs.rs/axum/latest/axum/extract/ws/enum.Message.html), which we create by [converting from tungstenite's `Message`](https://github.com/tokio-rs/axum/blob/main/axum/src/extract/ws.rs#L447-L459). But in tungstenite 0.17 I see `Message` has a new `Frame` variant which seems rather big. It has related types like headers and opcodes. So I'm not sure how to handle it.

I'm not very familiar with the internals of WebSockets so I'm wondering if you have some advice on how I should update to 0.17 and handle `Frame`. Should I copy/paste your code and convert between the types, like I do today? Or can `Frame` somehow be merged into one of the other variants, or perhaps ignored entirely?

**Comment by davidpdrsn** [comment]
Thanks for the quick response!

> It cannot occur when you read messages from the WebSocket, but it can be used when you want to send the raw frames (e.g. you want to send the frames to the WebSocket without composing the full message first)

Ah I see! That sounds like axum could perhaps just ignore `Frame`s and poll the stream for the next message if it receives one. Do you think that would be appropriate?

> Perhaps the best way for us to simplify this thing and make it "compatible" with axum would be feature-gating the raw frames (e.g. you could disable the feature when using tungstenite in axum).

That would be great! However I don't think a cargo feature would work since they're global. So if another dependency in the tree enables that feature axum would fail to build. Not sure if there are other solutions 🤔

**Comment by application-developer-DA** [comment]
> Ah I see! That sounds like axum could perhaps just ignore Frames and poll the stream for the next message if it receives one. Do you think that would be appropriate?

Yes, this is a viable approach :)

> That would be great! However I don't think a cargo feature would work since they're global. So if another dependency in the tree enables that feature axum would fail to build. Not sure if there are other solutions 🤔

Hmm, interesting. I thought this problem has been solved in `cargo` (but maybe I'm wrong, I just remember reading discussions somewhere in `rust-lang` about it and I don't remember what was decided there, e.g. I think I saw somewhere in a roadmap or "This Week In Rust" that there would be an option to fetch different versions so that each dependency uses its own version in case there is a discrepancy between features).

**Comment by davidpdrsn** [comment]
Thanks for your help! I believe I have the info I need now 😊

**Comment by jplatte** [comment]
> Hmm, interesting. I thought this problem has been solved in `cargo`

What changed is regular deps and host-deps (build-deps and proc-macros) no longer have their features unified and features activated through dev-deps are no longer applied for regular non-test builds. However, two regular (runtime) dependencies to the same crate from different places in the dependency tree will still have their features unified.

If that wasn't the case, which features of a dependency you activate would be part of your own public API since two versions of one crate compiled different features are different crates to the compiler, and as such not compatible. It would also lead to a lot of extra stuff being compiled for little benefit. (the big benefit in the host-dep / dev-dep case is you can enable std-dependent features for compile-time dependencies and testing when targeting a no_std target)
